server:
  port: 9001

spring:
  cloud:
    # add functions
#    function:
#      stream:
#        processor:
#          name: fizzBuzzProcessor
    stream:
      function:
        definition: fizzBuzzProducer;fizzBuzzProcessor;fizzBuzzConsumer
        bindings:
          toUpperCase|wrapInQuotes-in-0: quotedUpperCaseInput
#          toUpperCase|wrapInQuotes-out-0: quotedUpperCaseOutput
      bindings:
        fizzBuzzProducer-out-0:
          destination: numbers
        fizzBuzzProcessor-in-0:
          destination: numbers
        fizzBuzzProcessor-out-0:
          destination: fizz-buzz
        fizzBuzzConsumer-in-0:
          destination: fizz-buzz
#        quotedUpperCaseInput:
#          destination: caseInput
        quotedUpperCaseOutput:
          destination: caseOutput
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
